### ISSUE TITLE
Funcionalidad de la ventana para mostrar los usuarios registrados en forma de ítems

### ISSUE THREAD

**Issue by jpmvalencia** [jpmvalencia/Clase9#12]
Construir una ventana para ver los usuarios que se han registrado, debe mostrar los botones en forma de ítems de a 3 por dila y cada botón debe mostrar la cédula del usuario registrado. Hacer el botón para navegar de la centana1.py a esta nueva ventana2.py y de esta nueva ventana2.py hacer el botón para volver a la ventana1.py

**Comment by Ricardozapata20** [comment]
de una mi so. Voy a ver esos videos a ver cuanto se me demora en aparecer un error fatal

**Comment by Ricardozapata20** [comment]
de una mi so. Voy a ver esos videos a ver cuanto se me demora en aparecer un error fatal
